const BOOKINGS_TYPES = {
  ACCOMMODATION: "ACCOMMODATION",
  ALL: "ALL",
  FLIGHT: "FLIGHT",
  EXPERIENCE: "EXPERIENCE",
  RENTAL: "RENTAL",
  TRANSFER: "TRANSFER",
  PACKAGES: "PACKAGES",
  AIRPORT_HOTEL_TRANSFERS: "AIRPORT_HOTEL_TRANSFERS",
};

export default BOOKINGS_TYPES;
