export const BUYER_GROUB_TYPES = {
    GENERAL: "GENERAL",
    PALL: "PALL",
}

export const REFUNDABLE_NONREFUNDABLE = {
    REFUNDABLE_NON_REFUNDABLE: "REFUNDABLE_NON_REFUNDABLE",
    REFUNDABLE_ONLY: "REFUNDABLE_ONLY",
    NON_REFUNDABLE_ONLY: "NON_REFUNDABLE_ONLY",
};

export const OFFICER_TYPE = {
    AGENT: "AGENT",
    SUPPLIER: "SUPPLIER",
};