const EVENT_PEOPLE_TYPES = {
    AUDIENCE: "AUDIENCE",
    SPEAKER: "SPEAKER",
    SPONSOR: "SPONSOR",
    USER: "USER",
    VIP: "VIP",
    EXPOSITOR: "EXPOSITOR",
    ATEENDEE: "ATEENDEE",
    BLOCKED: "BLOCKED",
}

export default EVENT_PEOPLE_TYPES;