const EXPERIANCE_TYPES = {
  TOUR_ACTIVITY: "Tour/Activity",
  TRANSPORTATION: "Transportation",
  EVENT: "Event",
};

const AVAILABILITY_TYPES = {
  DATE_AND_TIME: "DATES_AND_TIME",
  PASS: "PASS",
  FREE_SALE: "FREE_SALE",
};

const CAPACITY_TYPES = {
  FREE_SALE: "FREE_SALE",
  LIMITED_NUMBER: "LIMITED_NUMBER",
  ON_REQUEST: "ON_REQUEST",
};

const REPEAT_TYPES = {
  WEEKLY: "WEEKLY",
  HOURLY: "HOURLY",
  DAILY: "DAILY",
  NO_REPEAT: "NO_REPEAT",
};

const PICK_UP_TYPES = {
  MEET_ON_LOCATION: "MEET_ON_LOCATION",
  PICK_UP_ONLY: "PICK_UP_ONLY",
  MEET_ON_LOCATION_OR_PICK_UP: "MEET_ON_LOCATION_OR_PICK_UP",
};

const PASSENGER_PRICE_TYPE = {
  PER_PERSON: "perPerson",
  PER_BOOKING: "perBooking",
};

const CANCELLATION_POLICY = {
  FREE_CANCELLATION: "Free_Cancellation",
  NON_REFUNDABLE_BOOKINGS: "Non_Refundable_Bookings",
  PARTIAL_REFUNDS: "Partial_Refunds",
};

const CANCELLATION_POLICY_PERIOD_TYPE = {
  AFTER_RESRVATION: "AFTER_RESRVATION",
  BEFORE_CHECK_IN: "BEFORE_CHECK_IN",
};


const CANCELLATION_POLICY_DATE_RANGE_TYPES = {
  RESTRICTED_DATE_RANGE: "RESTRICTED_DATE_RANGE",
  NO_RESTRICTIONS: "NO_RESTRICTIONS",
};

export {
  EXPERIANCE_TYPES,
  AVAILABILITY_TYPES,
  CAPACITY_TYPES,
  REPEAT_TYPES,
  PICK_UP_TYPES,
  PASSENGER_PRICE_TYPE,
  CANCELLATION_POLICY,
  CANCELLATION_POLICY_PERIOD_TYPE,
  CANCELLATION_POLICY_DATE_RANGE_TYPES
};
