export const HOTEL_CANCELLATION_TYPES = {
  FREE_CANCELLATION: "FREE_CANCELLATION",
  NON_REFUNDABLE: "NON_REFUNDABLE",
  PARTIAL_REFUND: "PARTIAL_REFUND",
};
export const HOTEL_CANCELLATION_APPLICABLE_DATE_RANGE_TYPES = {
  RESTRICTED_DATE_RANGE: "RESTRICTED_DATE_RANGE",
  NO_RESTRICTIONS: "NO_RESTRICTIONS",
};

export const HOTEL_CANCELLATION_PERIOD_TYPES = {
  AFTER_RESRVATION: "AFTER_RESRVATION",
  BEFORE_CHECK_IN: "BEFORE_CHECK_IN",
};
