export const TEMPLATE_TYPES = {
  WELCOMING: "WELCOMING",
  ENGAGEMENT: "ENGAGEMENT",
  FEEDBACK: "FEEDBACK",
  UPSELL: "UPSELL",
  REMINDER: "REMINDER",
  OTHER: "OTHER",
};

export const ENGAGEMENTS_ACTIONS_TYPES = {
  PRE_TRIP_ARRIVAL: "PRE_TRIP_ARRIVAL",
  PRE_TRIP_BOOKING_DATE: "PRE_TRIP_BOOKING_DATE",
  POST_TRIP_DEPARTURE: "POST_TRIP_DEPARTURE",
  DAY_MESSAGE: "DAY_MESSAGE",
  ITEM_MESSAGE: "ITEM_MESSAGE",
};

export const ENGAGEMENTS_SCHEDULE = {
  BEFORE: "BEFORE",
  AFTER: "AFTER",
};

export const ENGAGEMENTS_PROVIDER = {
  EMAIL: "EMAIL",
  WHATSAPP: "WHATSAPP",
};


export const PACKAGE_ENGAGEMENTS_MESSAGE_TYPES = {
  PRE_TRIP: "PRE_TRIP",
  POST_TRIP: "POST_TRIP",
  DAY: "DAY",
}