export const PACKAGE_OFFERED_TYPES = {
  RECURRING_TRIP: "RECURRING_TRIP",
  ONE_TIME: "ONE_TIME",
};

export const PACKAGE_AVAILABILITY_TYPES = {
  LIMITED: "LIMITED",
  UNLIMITED: "UNLIMITED",
  UNAVAILABEL: "UNAVAILABEL",
};

export const PACKAGE_ITEMS_TYPES = {
  ACCOMODATION: "ACCOMODATION",
  FLIGHT: "FLIGHT",
  TRANSFER: "TRANSFER",
  CAR_RIDE: "CAR_RIDE",
  EXPERIENCE: "EXPERIENCE",
};


export const PACKAGE_LIBRARY_ITEMS_TYPES = {
  SINGLE: "SINGLE",
  CHANGEABLE_BY_LOCATION: "CHANGEABLE_BY_LOCATION",
  SELECT_ONE_FROM_LIST : "SELECT_ONE_FROM_LIST",
};


export const PACKAGE_LIBRARY_ITEMS_STATIC_TYPES = {
  SINGLE: "SINGLE",
  SELECT_ONE_FROM_LIST : "SELECT_ONE_FROM_LIST",
};