const TYPE_OF_ANSWER = {
  SHORT_TEXT: "SHORT_TEXT",
  LONG_TEXT: "LONG_TEXT",
  NUMBER: "NUMBER",
  CHECKBOX: "CHECKBOX",
  DATE: "DATE",
  LIST_OF_OPTIONS: "LIST_OF_OPTIONS",
};

export default TYPE_OF_ANSWER;
